name = "my-worker"

main = "src/index.js"  # or whatever your entry file is
compatibility_flags = ["nodejs_compat"]

# Optional: uncomment if you want to deploy
# account_id = "your-cloudflare-account-id"
# workers_dev = true
