name = "my-worker"


compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

# Optional: uncomment if you want to deploy
# account_id = "your-cloudflare-account-id"
# workers_dev = true
