name = "my-worker"

compatibility_date = "2025-09-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Optional: uncomment if you want to deploy
# account_id = "your-cloudflare-account-id"
# workers_dev = true
